// pool.js
// 등급: n, r, sr, ssr, special, hidden, ?(black)

window.GILKEMON_POOL = [
  //n 7
  {
    id: "N-01",
    grade: "n",
    name: "석우",
    type: "내 청춘에게 고함",
    line: "“오늘은 여기까지면 됐죠.”",
    desc: "20대 청춘의 방황과 고민을 다룬다.",
    ballImg: "./assets/balls/n.png",
    charImg: "./assets/chars/석우.png",
  },
   {
    id: "N-02",
    grade: "n",
    name: "박문수",
    type: "강철중: 공공의 적 1-1",
    line: "“잠깐 나 좀 볼까?” ",
    desc: "이원술의 오른팔이자 서브 빌런.\n후반부 형사들과의 충돌 중 사망한 것으로 추정.",
    ballImg: "./assets/balls/n.png",
    cardGif: "./assets/chars/박문수.gif",
    charImg: "./assets/chars/박문수.png",
  },
   {
    id: "N-03",
    grade: "n",
    name: "히다카 신스케",
    type: "모던보이",
    line: "“얼마만이야”",
    desc: "조선총독부 고등 검사이면서\n 조선인인 해명과 절친한 사이.",
    ballImg: "./assets/balls/n.png",
    cardGif: "./assets/chars/히다타.gif",
    charImg: "./assets/chars/H-SSK.png",
  },
     {
    id: "N-04",
    grade: "n",
    name: "흥선대원군",
    type: "도리화가",
    line: "“소리가 좋구나.”",
    desc: "진채선의 재능을 알아보고 \n 그녀를 궁에 머물게 한다.",
    ballImg: "./assets/balls/n.png",
    cardGif: "./assets/chars/흥선.gif",
    charImg: "./assets/chars/흥선.png",
  },
     {
    id: "N-05",
    grade: "n",
    name: "철수",
    type: "문을 여는 법",
    line: "“열면 안 되는 문 같은 건 없어.\n어떤 일들은\n너를 단단하게 해줄 거야”",
    desc: "자립준비청년 '하늘'을 돕는 \n보육원 친구로 위로와 희망을 전한다.",
    ballImg: "./assets/balls/n.png",
    cardGif: "./assets/chars/철수2.png",
    charImg: "./assets/chars/철수.png",
  },
     {
    id: "N-06",
    grade: "n",
    name: "김병태",
    type: "내 이름은 김삼순",
    line: "“상처받기 싫으면\n사랑하지 마.”",
    desc: "의사, 진헌과 희진의 친구",
    ballImg: "./assets/balls/n.png",
    charImg: "./assets/chars/김병태.png",
  },
     {
    id: "N-07",
    grade: "n",
    name: "태산",
    type: "연인",
    line: "“저 당신을 사랑합니다.”",
    desc: "말수가 적고 묵묵히 짝사랑하며 곁을 지킨다.",
    ballImg: "./assets/balls/n.png",
    cardGif: "./assets/chars/태산.gif",
    charImg: "./assets/chars/태산.png",
  },

  //r 9
    {
    id: "R-01",
    grade: "r",
    name: "송재민",
    type: "후회하지 않아",
    line: "“그래도 나 너 사랑해.\n떠나도 되는데 그러진 않았어.”",
    desc: "결혼을 앞둔 약혼녀가 있지만 \n 수민을 진심으로 사랑한다.",
    ballImg: "./assets/balls/r.png",
    cardGif: "./assets/chars/송재민2.gif",
    charImg: "./assets/chars/송재민.png",
  },
     {
    id: "R-02",
    grade: "r",
    name: "강무",
    type: "미인도",
    line: "“봐. 네가 조선 땅에서 제일 아름다워.”",
    desc: "사랑을 운명처럼 받아들인다.\n거칠지만 순수한 사랑을 보인다. ",
    ballImg: "./assets/balls/r.png",
    cardGif: "./assets/chars/강무.gif",
    charImg: "./assets/chars/강무.png",
  },
     {
    id: "R-03",
    grade: "r",
    name: "임수인",
    type: "폭풍전야",
    line: "“더 이상 잃을 것도,\n 겁날 것도 없어.”",
    desc: "상처를 안고 산다.\n사랑을 피하지 않는다. ",
    ballImg: "./assets/balls/r.png",
    cardGif: "./assets/chars/임수인.gif",
    charImg: "./assets/chars/임수인.png",
  },
     {
    id: "R-04",
    grade: "r",
    name: "이재준",
    type: "헌트",
    line: "“피해!”",
    desc: "동경지부 요원 3",
    ballImg: "./assets/balls/r.png",
    cardGif: "./assets/chars/이재준.jpg",
    charImg: "./assets/chars/이재준.png",
  },
     {
    id: "R-05",
    grade: "r",
    name: "강호령",
    type: "브로큰",
    line: "“지켜야 한다,\n내 소설과 명예를.”",
    desc: "소설과 자신의 명예를 지키기 \n위해 사라진 사람을 찾아 나선다.",
    ballImg: "./assets/balls/r.png",
    cardGif: "./assets/chars/강호령.gif",
    charImg: "./assets/chars/강호령.png",
  },
     {
    id: "R-06",
    grade: "r",
    name: "유지안",
    type: "굿바이 솔로",
    line: "“사랑은 안 변하지만,\n사람 마음은 변해.”",
    desc: "냉소적이지만 내면의 상처를 가졌다.",
    ballImg: "./assets/balls/r.png",
    cardGif: "./assets/chars/유지안.gif",
    charImg: "./assets/chars/유지안.png",
  },
     {
    id: "R-07",
    grade: "r",
    name: "김준기",
    type: "꽃 피는 봄이 오면",
    line: "“기다릴 줄도 알아야 합니다.”",
    desc: "이성적이며 사건을 \n냉철하게 파악하고 처리하는 검사.",
    ballImg: "./assets/balls/r.png",
    cardGif: "./assets/chars/김준기.gif",
    charImg: "./assets/chars/김준기.png",
  },
     {
    id: "R-08",
    grade: "r",
    name: "긴장남",
    type: "오케이마담",
    line: "“저기요 지금 비행기 돌리면 안되나요?”",
    desc: "고소 공포증으로 인해\n 비행기를 무서워한다.",
    ballImg: "./assets/balls/r.png",
    cardGif: "./assets/chars/긴장남.gif",
    charImg: "./assets/chars/긴장남.png",
  },
     {
    id: "R-09",
    grade: "r",
    name: "박민걸",
    type: "기묘한 가족",
    line: "“줄을 서시오!!!”",
    desc: "좀비가 된 쫑비와 아버지 만덕의\n 특성을 이용해 돈벌이를 꾀한다.",
    ballImg: "./assets/balls/r.png",
    cardGif: "./assets/chars/박민걸.gif",
    charImg: "./assets/chars/박민걸.png",
  },
//sr 
    {
    id: "SR-01",
    grade: "sr",
    name: "심건욱",
    type: "나쁜남자",
    line: "“날 건드리는 사람은...\n내가 가만두고 볼 것 같아?”",
    desc: "복수를 위해 냉혹하게 살아간다. 겉은 차갑지만 내면에는 깊은 상처, 고독을 지녔다.",
    ballImg: "./assets/balls/sr.png",
    cardGif: "./assets/chars/심건욱.gif",
    charImg: "./assets/chars/심건욱.png",
  },
    {
    id: "SR-02",
    grade: "sr",
    name: "장사정",
    type: "해적: 바다로 간 산적",
    line: "“나 장사정이야!\n송악 미친 호랑이!”",
    desc: "전직 군관 출신 산적 두목으로 능글맞은 성격 뒤에 뛰어난 무력과 강단을 지녔다. 국새를 삼킨 고래를 쫓아 바다로 나선다.",
    ballImg: "./assets/balls/sr.png",
    cardGif: "./assets/chars/장사정.gif",
    charImg: "./assets/chars/장사정.png",
  },
      {
    id: "SR-03",
    grade: "sr",
    name: "최현수",
    type: "비상선언",
    line: "“활주로를 열어주세요.”",
    desc: "KI501편 부기장. 기내 테러와 바이러스 사태 속에서 책임감으로 조종간을 잡고 위기를 수습하다가 결국 기장 역할까지 맡게 된다.",
    ballImg: "./assets/balls/sr.png",
    cardGif: "./assets/chars/최현수.gif",
    charImg: "./assets/chars/최현수.png",
  },
     {
    id: "SR-04",
    grade: "sr",
    name: "한이수",
    type: "상어",
    line: "“상어는 부레가 없어.\n그래서 끊임없이 움직여야 해.”",
    desc: "아버지의 죽음에 얽힌 진실을 밝히기 위해 냉혹한 복수를 준비한다.사랑하는 여인과 가족 앞에서는 흔들리면서도 끝내 복수의 길을 포기하지 않는다.",
    ballImg: "./assets/balls/sr.png",
    cardGif: "./assets/chars/한이수.gif",
    charImg: "./assets/chars/한이수.png",
  },
    {
    id: "SR-05",
    grade: "sr",
    name: "허임",
    type: "명불허전",
    line: "“살아야 한다.\n어떻게든 살아야 한다.”",
    desc: "신분의 한계에 좌절한 조선의 천재 침술가로, 죽음의 위기마다 조선과 현대를 오가며 성장한다.",
    ballImg: "./assets/balls/sr.png",
    cardGif: "./assets/chars/허임.gif",
    charImg: "./assets/chars/허임.png",
  },
   {
    id: "SR-06",
    grade: "sr",
    name: "윤정민",
    type: "악연",
    line: "“그냥... 악연이라고 생각해.”",
    desc: "병원 의사로 일하면서 빚과 돈 때문에 불법 장기 밀매에 가담한다.",
    ballImg: "./assets/balls/sr.png",
    cardGif: "./assets/chars/윤정민.gif",
    charImg: "./assets/chars/윤정민.png",
  },
    {
    id: "SR-07",
    grade: "sr",
    name: "우진",
    type: "보호자",
    line: "“다 소용없어.\n어차피 넌 죽을 거니까”",
    desc: "‘세탁기’라 불리는 성공률 100%의 청부살인업자로, 광기 어린 웃음과 불안정한 정신 상태다.",
    ballImg: "./assets/balls/sr.png",
    cardGif: "./assets/chars/우진.jpg",
    charImg: "./assets/chars/우진.png",
  },
  {
    id: "SR-REFUSE",
    grade: "sr",
    name: "이강수",
    type: "어느날",
    line: "“내가 널 어떻게 잊어...”",
    desc: "곁을 지키는 데 익숙하다.\n 떠나간 사람을 잊지 못한다.",
    ballImg: "./assets/balls/sr.png",
    cardGif: "./assets/chars/이강수.gif",
    charImg: "./assets/chars/이강수.png",
    special: "REFUSE", //떠나는 캐릭터
  },

  {
  id: "SR-CHOICE-01",
  grade: "sr",
  name: "강재혁",
  type: "방어형",
  desc: "결정된 선택을 끝까지 유지하고 있다.\n 버티고 있다.",
  line: "“사실 나도 무서워...\n 내 얘기 조금만 들어줄래?”", // 첫 카드에 기본으로 보일 대사
  ballImg: "./assets/balls/sr.png",
  cardGif: "./assets/chars/강재혁메인.gif",
  charImg: "./assets/chars/강재혁.png",
  

  special: "CHOICE_SR",
  choice: true, // 추가 (동작 실행)

  // 그래 선택
  choiceYesImg: "./assets/chars/강재혁고마워.gif",
  choiceYesLine: "고마웠어. 잊지 않고 기억해주라...",

  // 아니 선택
  choiceNoImg: "./assets/chars/강재혁아니.gif",
  choiceNoLine: "... 무서워. 내가 왜 죽어야 돼.",
},
   
  {
    id: "SSR-SPECIAL-01",
    grade: "ssr",
    name: "특수 SSR",
    type: "압박형",
    line: "“끝까지 본다면.”",
    desc: "특수 SSR: 다음 터치에 타이핑 연출로 (이미지+이름+대사) 재노출 예정.",
    ballImg: "./assets/balls/ssr.png",
    charImg: "./assets/chars/sample-ssr.png",
    dexGif: "./assets/chars/송하영픽셀.gif",
    special: "SPECIAL_SSR",
  },
     {
    id: "SSR-01",
    grade: "sr",
    name: "H-R",
    type: "관찰형",
    line: "“정리가 필요하겠군요.”",
    desc: "선택을 쉽게 내리지 않는다.\n질서가 무너지는 상황을 경계한다.",
    ballImg: "./assets/balls/ssr.png",
    charImg: "./assets/chars/sample.png",
  },
     {
    id: "SPECIAL-01",
    grade: "special",
    name: "H-R",
    type: "관찰형",
    line: "“정리가 필요하겠군요.”",
    desc: "선택을 쉽게 내리지 않는다.\n질서가 무너지는 상황을 경계한다.",
    cardGif: "./assets/chars/N-01.gif",
    ballImg: "./assets/balls/special.png",
    charImg: "./assets/chars/sample.png",
  },
     {
    id: "SPECIAL-02",
    grade: "special",
    name: "무잔",
    type: "균형형",
    line: "“아직도 가끔 생각나.”",
    desc: "미각은 정확하다.\n감정은 정리하지 않았다",
    ballImg: "./assets/balls/special.png",
    charImg: "./assets/chars/무잔.png",
    cardGif: "./assets/chars/N-01.gif",
    textBoxBg: "rgba(160, 80, 60, .55)",
  },
  {
  id: "SPECIAL-03",
  grade: "special",
  name: "스페셜1",
  type: "관찰형",
  line: "“터치하면 타이핑으로 뜬다.”",
  desc: "....",
  ballImg: "./assets/balls/special.png",
  charImg: "./assets/chars/special1.png",

  special: "SPECIAL_TYPING", // ✅ 이 한 장에만!
},

  {
    id: "BLACK-01",
    grade: "?",
    name: "BLACK",
    type: "교란형",
    line: "“……”",
    desc: "블랙: 히스토리를 지우는 이벤트가 뒤따릅니다.",
    ballImg: "./assets/balls/black.png",
    charImg: "./assets/chars/sample-black.gif",
    special: "BLACK",
    eventImg: "./assets/events/black-event.png",
  },
];
