// pool.js
// 등급: n, r, sr, ssr, special, hidden, ?(black)

window.GILKEMON_POOL = [
  //n 7
  {
    id: "N-01",
    grade: "n",
    name: "석우",
    type: "내 청춘에게 고함",
    line: "“오늘은 여기까지면 됐죠.”",
    desc: "20대 청춘의 방황과 고민을 다룬다.",
    ballImg: "./assets/balls/n.png",
    charImg: "./assets/chars/석우.png",
  },
   {
    id: "N-02",
    grade: "n",
    name: "박문수",
    type: "강철중: 공공의 적 1-1",
    line: "“잠깐 나 좀 볼까?” ",
    desc: "이원술의 오른팔이자 서브 빌런.\n후반부 형사들과의 충돌 중 사망한 것으로 추정.",
    ballImg: "./assets/balls/n.png",
    cardMp4: "./assets/chars/박문수.mp4",
    cardGif: "./assets/chars/박문수.gif",
    charImg: "./assets/chars/박문수.png",
  },
   {
    id: "N-03",
    grade: "n",
    name: "히다카 신스케",
    type: "모던보이",
    line: "“얼마만이야”",
    desc: "조선총독부 고등 검사이면서\n 조선인인 해명과 절친한 사이.",
    ballImg: "./assets/balls/n.png",
    cardMp4: "./assets/chars/히다카.mp4",
    cardGif: "./assets/chars/히다타.gif",
    charImg: "./assets/chars/H-SSK.png",
  },
     {
    id: "N-04",
    grade: "n",
    name: "흥선대원군",
    type: "도리화가",
    line: "“소리가 좋구나.”",
    desc: "진채선의 재능을 알아보고 \n 그녀를 궁에 머물게 한다.",
    ballImg: "./assets/balls/n.png",
    cardMp4: "./assets/chars/흥선.mp4",
    cardGif: "./assets/chars/흥선.gif",
    charImg: "./assets/chars/흥선.png",
  },
     {
    id: "N-05",
    grade: "n",
    name: "철수",
    type: "문을 여는 법",
    line: "“열면 안 되는 문 같은 건 없어.\n어떤 일들은\n너를 단단하게 해줄 거야”",
    desc: "자립준비청년 '하늘'을 돕는 \n보육원 친구로 위로와 희망을 전한다.",
    ballImg: "./assets/balls/n.png",
    cardGif: "./assets/chars/철수2.png",
    charImg: "./assets/chars/철수.png",
  },
     {
    id: "N-06",
    grade: "n",
    name: "김병태",
    type: "내 이름은 김삼순",
    line: "“상처받기 싫으면\n사랑하지 마.”",
    desc: "의사, 진헌과 희진의 친구",
    ballImg: "./assets/balls/n.png",
    charImg: "./assets/chars/김병태.png",
  },
     {
    id: "N-07",
    grade: "n",
    name: "태산",
    type: "연인",
    line: "“저 당신을 사랑합니다.”",
    desc: "말수가 적고 묵묵히 짝사랑하며 곁을 지킨다.",
    ballImg: "./assets/balls/n.png",
    cardMp4: "./assets/chars/태산.mp4",
    cardGif: "./assets/chars/태산.gif",
    charImg: "./assets/chars/태산.png",
  },

  //r 9
    {
    id: "R-01",
    grade: "r",
    name: "송재민",
    type: "후회하지 않아",
    line: "“그래도 나 너 사랑해.\n떠나도 되는데 그러진 않았어.”",
    desc: "결혼을 앞둔 약혼녀가 있지만 \n 수민을 진심으로 사랑한다.",
    ballImg: "./assets/balls/r.png",
    cardMp4: "./assets/chars/송재민.mp4",
    cardGif: "./assets/chars/송재민2.gif",
    charImg: "./assets/chars/송재민.png",
  },
     {
    id: "R-02",
    grade: "r",
    name: "강무",
    type: "미인도",
    line: "“봐. 네가 조선 땅에서 제일 아름다워.”",
    desc: "사랑을 운명처럼 받아들인다.\n거칠지만 순수한 사랑을 보인다. ",
    ballImg: "./assets/balls/r.png",
    cardMp4: "./assets/chars/강무.mp4",
    cardGif: "./assets/chars/강무.gif",
    charImg: "./assets/chars/강무.png",
  },
     {
    id: "R-03",
    grade: "r",
    name: "임수인",
    type: "폭풍전야",
    line: "“더 이상 잃을 것도,\n 겁날 것도 없어.”",
    desc: "상처를 안고 산다.\n사랑을 피하지 않는다. ",
    ballImg: "./assets/balls/r.png",
    cardMp4: "./assets/chars/임수인.mp4",
    cardGif: "./assets/chars/임수인.gif",
    charImg: "./assets/chars/임수인.png",
  },
     {
    id: "R-04",
    grade: "r",
    name: "이재준",
    type: "헌트",
    line: "“피해!”",
    desc: "동경지부 요원 3",
    ballImg: "./assets/balls/r.png",
    cardGif: "./assets/chars/이재준.jpg",
    charImg: "./assets/chars/이재준.png",
  },
     {
    id: "R-05",
    grade: "r",
    name: "강호령",
    type: "브로큰",
    line: "“지켜야 한다,\n내 소설과 명예를.”",
    desc: "소설과 자신의 명예를 지키기 \n위해 사라진 사람을 찾아 나선다.",
    ballImg: "./assets/balls/r.png",
    cardMp4: "./assets/chars/강호령.mp4",
    cardGif: "./assets/chars/강호령.gif",
    charImg: "./assets/chars/강호령.png",
  },
     {
    id: "R-06",
    grade: "r",
    name: "유지안",
    type: "굿바이 솔로",
    line: "“사랑은 안 변하지만,\n사람 마음은 변해.”",
    desc: "냉소적이지만 내면의 상처를 가졌다.",
    ballImg: "./assets/balls/r.png",
    cardMp4: "./assets/chars/유지안.mp4",
    cardGif: "./assets/chars/유지안.gif",
    charImg: "./assets/chars/유지안.png",
  },
     {
    id: "R-07",
    grade: "r",
    name: "김준기",
    type: "꽃 피는 봄이 오면",
    line: "“기다릴 줄도 알아야 합니다.”",
    desc: "이성적이며 사건을 \n냉철하게 파악하고 처리하는 검사.",
    ballImg: "./assets/balls/r.png",
    cardMp4: "./assets/chars/김준기.mp4",
    cardGif: "./assets/chars/김준기.gif",
    charImg: "./assets/chars/김준기.png",
  },
     {
    id: "R-08",
    grade: "r",
    name: "긴장남",
    type: "오케이마담",
    line: "“저기요 지금 비행기 돌리면 안되나요?”",
    desc: "고소 공포증으로 인해\n 비행기를 무서워한다.",
    ballImg: "./assets/balls/r.png",
    cardMp4: "./assets/chars/긴장남.mp4",
    cardGif: "./assets/chars/긴장남.gif",
    charImg: "./assets/chars/긴장남.png",
  },
     {
    id: "R-09",
    grade: "r",
    name: "박민걸",
    type: "기묘한 가족",
    line: "“줄을 서시오!!!”",
    desc: "좀비가 된 쫑비와 아버지 만덕의\n 특성을 이용해 돈벌이를 꾀한다.",
    ballImg: "./assets/balls/r.png",
    cardMp4: "./assets/chars/박민걸.mp4",
    cardGif: "./assets/chars/박민걸.gif",
    charImg: "./assets/chars/박민걸.png",
  },
//sr 
    {
    id: "SR-01",
    grade: "sr",
    name: "심건욱",
    type: "나쁜남자",
    line: "“날 건드리는 사람은...\n내가 가만두고 볼 것 같아?”",
    desc: "복수를 위해 냉혹하게 살아간다. 겉은 차갑지만 내면에는 깊은 상처, 고독을 지녔다.",
    ballImg: "./assets/balls/sr.png",
    cardMp4: "./assets/chars/심건욱.mp4",
    cardGif: "./assets/chars/심건욱.gif",
    charImg: "./assets/chars/심건욱.png",
  },
    {
    id: "SR-02",
    grade: "sr",
    name: "장사정",
    type: "해적: 바다로 간 산적",
    line: "“나 장사정이야!\n송악 미친 호랑이!”",
    desc: "전직 군관 출신 산적 두목으로 능글맞은 성격 뒤에 뛰어난 무력과 강단을 지녔다. 국새를 삼킨 고래를 쫓아 바다로 나선다.",
    ballImg: "./assets/balls/sr.png",
    cardMp4: "./assets/chars/장사정.mp4",
    cardGif: "./assets/chars/장사정.gif",
    charImg: "./assets/chars/장사정.png",
  },
      {
    id: "SR-03",
    grade: "sr",
    name: "최현수",
    type: "비상선언",
    line: "“활주로를 열어주세요.”",
    desc: "KI501편 부기장. 기내 테러와 바이러스 사태 속에서 책임감으로 조종간을 잡고 위기를 수습하다가 결국 기장 역할까지 맡게 된다.",
    ballImg: "./assets/balls/sr.png",
    cardMp4: "./assets/chars/최현수.mp4",
    cardGif: "./assets/chars/최현수.gif",
    charImg: "./assets/chars/최현수.png",
  },
     {
    id: "SR-04",
    grade: "sr",
    name: "한이수",
    type: "상어",
    line: "“상어는 부레가 없어.\n그래서 끊임없이 움직여야 해.”",
    desc: "아버지의 죽음에 얽힌 진실을 밝히기 위해 냉혹한 복수를 준비한다.사랑하는 여인과 가족 앞에서는 흔들리면서도 끝내 복수의 길을 포기하지 않는다.",
    ballImg: "./assets/balls/sr.png",
    cardMp4: "./assets/chars/한이수.mp4",
    cardGif: "./assets/chars/한이수.gif",
    charImg: "./assets/chars/한이수.png",
  },
    {
    id: "SR-05",
    grade: "sr",
    name: "허임",
    type: "명불허전",
    line: "“살아야 한다.\n어떻게든 살아야 한다.”",
    desc: "신분의 한계에 좌절한 조선의 천재 침술가로, 죽음의 위기마다 조선과 현대를 오가며 성장한다.",
    ballImg: "./assets/balls/sr.png",
    cardMp4: "./assets/chars/허임.mp4",
    cardGif: "./assets/chars/허임.gif",
    charImg: "./assets/chars/허임.png",
  },
   {
    id: "SR-06",
    grade: "sr",
    name: "윤정민",
    type: "악연",
    line: "“그냥... 악연이라고 생각해.”",
    desc: "병원 의사로 일하면서 빚과 돈 때문에 불법 장기 밀매에 가담한다.",
    ballImg: "./assets/balls/sr.png",
    cardMp4: "./assets/chars/윤정민.mp4",
    cardGif: "./assets/chars/윤정민.gif",
    charImg: "./assets/chars/윤정민.png",
  },
    {
    id: "SR-07",
    grade: "sr",
    name: "우진",
    type: "보호자",
    line: "“다 소용없어.\n어차피 넌 죽을 거니까”",
    desc: "‘세탁기’라 불리는 성공률 100%의 청부살인업자로, 광기 어린 웃음과 불안정한 정신 상태다.",
    ballImg: "./assets/balls/sr.png",
    cardGif: "./assets/chars/우진.jpg",
    charImg: "./assets/chars/우진.png",
  },
  {
    id: "SR-REFUSE",
    grade: "sr",
    name: "이강수",
    type: "어느날",
    line: "“내가 널 어떻게 잊어...”",
    desc: "곁을 지키는 데 익숙하다.\n 떠나간 사람을 잊지 못한다.",
    ballImg: "./assets/balls/sr.png",
    cardMp4: "./assets/chars/이강수.mp4",
    cardGif: "./assets/chars/이강수.gif",
    charImg: "./assets/chars/이강수.png",
    special: "REFUSE", //떠나는 캐릭터
  },

  {
  id: "SR-CHOICE-01",
  grade: "sr",
  name: "강재혁",
  type: "판도라",
  desc: "결정된 선택을 끝까지 유지하고 있다.\n 버티고 있다.",
  line: "“사실 나도 무서워...\n 내 얘기 조금만 들어줄래?”", // 첫 카드에 기본으로 보일 대사
  ballImg: "./assets/balls/sr.png",
  cardMp4: "./assets/chars/강재혁메인.mp4",
  charImg: "./assets/chars/강재혁.png",
  

  special: "CHOICE_SR",
  choice: true, // 추가 (동작 실행)

  // 그래 선택
  eventMp4: "./assets/events/gang-yes.mp4",
  choiceYesLine: "고마웠어. 잊지 않고 기억해주라...",

  // 아니 선택
  eventNoMp4: "./assets/events/gang-no.mp4",
  choiceNoLine: "... 무서워. 내가 왜 죽어야 돼.",
},

//ssr 
      {
    id: "SSR-01",
    grade: "sr",
    name: "비담",
    type: "선덕여왕",
    line: "“덕만까지 70보... 덕만까지 30보... 덕만까지 10보....”",
    desc: "미실의 아들이자 덕만을 연모한다.\n사랑과 대의 사이에서 갈등하며 순수함과 광기를 동시에 보여준다.",
    ballImg: "./assets/balls/ssr.png",
    cardMp4: "./assets/chars/비담.mp4",
    charImg: "./assets/chars/비담.png", 
  },
   {
    id: "SSR-02",
    grade: "sr",
    name: "이윤",
    type: "도적",
    line: "“이렇게 가만히 계실 겁니까?”",
    desc: "일본군 출신이지만 과거의 죄를 깨닫고 조선인들을 지키기 위해 도적단을 이끄는 최강의 전사가 되었다. 압도적인 전투력으로 숙적 이광일과 맞서 승리하며 정의의 편에 선다.",
    ballImg: "./assets/balls/ssr.png",
    cardMp4: "./assets/chars/이윤.mp4",
    charImg: "./assets/chars/이윤.png",
  },
     {
    id: "SSR-03",
    grade: "sr",
    name: "정재곤",
    type: "무뢰한",
    line: "“새해 복 많이 받아라.”",
    desc: "범인 검거라는 목표와 사랑 사이에서 갈등한다. 범인을 잡기 위해선 수단과 방법을 가리지 않는다.",
    ballImg: "./assets/balls/ssr.png",
    cardMp4: "./assets/chars/정재곤.mp4",
    cardGif: "./assets/chars/정재곤.gif",
    charImg: "./assets/chars/정재곤.png",
  },
       {
    id: "SSR-04",
    grade: "sr",
    name: "허경훈",
    type: "클로젯",
    line: "“제가 좀 대단하거든요. \n근데 귀신보다 사람이 더 무서워요.”",
    desc: "능청스러우며 수다쟁이다. 하지만 본업에선 진지한 퇴마사 능력을 보여준다. ",
    ballImg: "./assets/balls/ssr.png",
    cardMp4: "./assets/chars/허경훈.mp4",
    charImg: "./assets/chars/허경훈.png",
  },
      {
    id: "SSR-05",
    grade: "sr",
    name: "반",
    type: "아일랜드",
    line: "“한순간만이라도 사람의 마음으로 살아보고 싶어”",
    desc: "정염귀들에게 대적하기 위해 정염귀의 피를 강제로 주입받고 '반인반요'가 되었다. 금강저를 주 무기로 사용하며 정염귀를 섬멸시킨다.",
    ballImg: "./assets/balls/ssr.png",
    cardMp4: "./assets/chars/반.mp4",
    charImg: "./assets/chars/반.png",
  },
    
       {
    id: "SSR-06",
    grade: "sr",
    name: "김해일",
    type: "열혈사제",
    line: "“용서는 당사자한테 찾아가서 해야지.\n성당에서 구하는 게 아니야.”",
    desc: "사건에 휘말려 국정원을 나오게 되고 조금이라도 속죄하기 위해 신부가 되었다. 외모는 은혜롭지만 승질은 드릅기 그지없다.",
    ballImg: "./assets/balls/ssr.png",
    cardMp4: "./assets/chars/김해일.mp4",
    charImg: "./assets/chars/김해일.png",
  },
  {
    id: "SSR-SPECIAL-01",
    grade: "ssr",
    name: "송하영",
    type: "악의 마음을 읽는 자들",
    line: "“범인의 입장이 되어보고 그들을 빨리 잡고 싶은 생각 뿐입니다.”",
    eline : "제가 그들의 입장이\n 되어보려고 했던게 맞는 걸까요. 사실 제가 가장 두려운건요,\n 나도 모르는 또 다른 내가\n 존재할지도 모른다는\n 불안감이였어요. \n나 또한 그들처럼 되는건 아닌지.",
    desc: "범죄자의 심리를 분석하는 프로파일러로, 냉철한 이성과 깊은 공감 능력을 지녔다. 잔혹한 범죄를 마주하며 흔들리면서도 끝까지 그들의 마음을 파헤치려 한다.",
    ballImg: "./assets/balls/ssr.png",
    cardMp4: "./assets/chars/송하영.mp4",
    charImg: "./assets/chars/송하영.png",
    dexGif: "./assets/events/송하영픽셀.gif",
    special: "SPECIAL_SSR",
  },
        {
    id: "SSR-07",
    grade: "sr",
    name: "이도",
    type: "트리거",
    line: "“아니, 그런 유토피아는 없어.\n 서로가 죽고 죽이는 상황들이 반복되는 지옥만 있을 뿐이지.”",
    desc: "특수부대 출신 순경으로 총기 트라우마를 안고 불법 총기 사건의 진실을 추적한다. 압도적인 전투력과 정의감으로 복수의 악순환을 막으며 절대 선의 상징이다.",
    ballImg: "./assets/balls/ssr.png",
    cardMp4: "./assets/chars/이도.mp4",
    charImg: "./assets/chars/이도.png",
  },
  
     {
    id: "SPECIAL-07",
    grade: "special",
    name: "탐탐이",
    type: "고양이",
    line: "“어흥.!!”",
    desc: "",
    ballImg: "./assets/balls/special.png",
    charImg: "./assets/chars/탐탐.png",
  },
     {
    id: "SPECIAL-06",
    grade: "special",
    name: "무잔",
    type: "균형형",
    line: "“아직도 가끔 생각나.”",
    desc: "미각은 정확하다.\n감정은 정리하지 않았다",
    ballImg: "./assets/balls/special.png",
    charImg: "./assets/chars/무잔.png",
    textBoxBg: "rgba(180, 86, 62, 0.69)",
  },
  {
  id: "SPECIAL-01",
  grade: "special",
  name: "이중권",
  type: "열혈사제",
  line: "“이유? 김해일이 너는 재수가 없어.”",
  eline : "대테러 1팀에서 사람 제일 많이 죽인건 너야. 열한명 애들 빼고도 1등인게 김해일이 너라고.",
  desc: "김해일을 트라우마에 빠지게 한 장본인.",
  ballImg: "./assets/balls/special.png",
  charImg: "./assets/chars/이중권.png",

  special: "SPECIAL_TYPING", // 이 한 장에만!
},
     {
    id: "SPECIAL-02",
    grade: "special",
    name: "황철범",
    type: "열혈사제",
    line: "“이런! 쪽수가 안 맞잖아.”",
    desc: "김해일과의 시작은 안 좋았지만, 이젠 그의 편에서 움직인다.",
    ballImg: "./assets/balls/special.png",
    charImg: "./assets/chars/황철범.png",
  },
       {
    id: "SPECIAL-03",
    grade: "special",
    name: "국영수",
    type: "악의 마음을 읽는 자들",
    line: "“하영아.. 다 좋은데 너 자신보다 중요한건 없어.”",
    desc: "송하영 본인보다 더 그를 걱정한다.\n 늘 그와 함께 있다.",
    ballImg: "./assets/balls/special.png",
    charImg: "./assets/chars/국영수.png",
  },
         {
    id: "SPECIAL-04",
    grade: "special",
    name: "정우주",
    type: "악의 마음을 읽는 자들",
    line: "“경위님. 제가 도울 거 있으면 말해주세요!”",
    desc: "국영수와 마찬가지로 송하영을 걱정한다.\n 늘 그의 한 발자국 뒤에 있다.",
    ballImg: "./assets/balls/special.png",
    charImg: "./assets/chars/국영수.png",
  },
       {
    id: "SPECIAL-05",
    grade: "special",
    name: "문백",
    type: "트리거",
    line: "“이도오... 어디 간거야?”",
    desc: "이도와 함께 있으면 공격력이 떨어지지만 항상 그의 곁에 있다.",
    ballImg: "./assets/balls/special.png",
    charImg: "./assets/chars/문백.png",
  },

  {
    id: "BLACK-01",
    grade: "?",
    name: "민태주",
    type: "살인자의 기억법",
    line: "“……안녕하세요?”",
    desc: "강화경찰서 정보과 소속 순경.",
    ballImg: "./assets/balls/black.png",
    cardMp4: "./assets/chars/민태주.mp4",
    charImg: "./assets/chars/민태주.png",
    special: "BLACK",
    eventMp4: "./assets/events/민태주.mp4",
  },
];
